baseurl = "https://samgil.es"
title = "samgiles"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Sam Giles"
    info = "Software Developer"
    description = "Blog"
    keywords = "blog,developer,personal,site reliability engineering,rust,sre,devops"

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = true

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Series see also post count
    maxSeeAlsoItems = 5


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/samgiles/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/SamuelGiles_/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 3
    url = "index.xml"
    rel = "alternate"
    type = "application/rss+xml"


# Menu links
[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "about"
    weight = 2
    url = "/about/"
